Добавление разметки
htmlacademy-htmlcss/2275815-sedona-37 pull request #2
Opened 2023-05-29 17:33 UTC by JowHenkel

2023-06-17 13:46 UTC, Kartaviy-arteom requested changes

2023-06-17 13:46 UTC, Kartaviy-arteom commented on catalog.html
> +  <link rel="stylesheet" href="../2275815-sedona-36/style/style.css">
тут путь нужно исправить, построить его от файла индекс, т.е будет просто "style/style.css"

2023-06-17 13:46 UTC, Kartaviy-arteom commented on catalog.html
> +      <img class="page-header-logo" alt="Логотип City of Sedona" src="./images/logo-sedona.svg">
можно сразу сделать alt под критерий https://up.htmlacademy.ru/htmlcss/37/criteries#ALLY-02 но на данном этапе это не обязательно

2023-06-17 13:46 UTC, Kartaviy-arteom commented on catalog.html
> +          <a class="navigation-link" href="">О Седоне</a>
href="#" для ссылок на страницы, которых у нас нет

2023-06-17 13:46 UTC, Kartaviy-arteom commented on catalog.html
> +              <img class="nav-search" alt="Поиск" src="./images/search.svg">
img тут не нужна, это декоративная графика, выполнится стилями или через svg https://up.htmlacademy.ru/htmlcss/37/criteries#IMG-01

2023-06-17 13:46 UTC, Kartaviy-arteom commented on catalog.html
> +          <p class="product-card-hotel">Гостиница</p>
лучше тут span

2023-06-17 13:46 UTC, Kartaviy-arteom commented on catalog.html
> +          <img class="rating-stars" src="images/stars.svg" alt="рейтинг Amara Resort & Spa">
img не нужен

2023-06-17 13:46 UTC, Kartaviy-arteom commented on catalog.html
> +          <p>...</p>
можно сделать span или ссылку, но не p

2023-06-17 13:46 UTC, Kartaviy-arteom commented on index.html
> +      </div>
div закрывается два раза

2023-06-17 13:46 UTC, Kartaviy-arteom commented on index.html
> +      <p class="advantages-reasons"></p>>Рассмотрим причины, по которым Седона круче, чем Гранд-Каньон!</p>
`<p class="advantages-reasons"></p>>`

2023-06-17 13:46 UTC, Kartaviy-arteom commented on index.html
> +    <div class="page-container">
для данной страницы, можно всю страницу поместить в один контейнер

2023-06-17 13:46 UTC, Kartaviy-arteom commented on index.html
> +      <img src="./images/welcome.svg" alt="Welcome to the  gorgeous">
одна img будет в разметке, остальная графика в стилях

2023-06-17 13:46 UTC, Kartaviy-arteom commented on index.html
> +      </ul>
эту часть можно выделить в секцию сервисы или что-то такое

2023-06-18 10:16 UTC, JowHenkel commented on catalog.html
> +  <link rel="stylesheet" href="../2275815-sedona-36/style/style.css">
Изменения везде внесла

2023-06-19 16:23 UTC, Kartaviy-arteom requested changes

2023-06-19 16:23 UTC, Kartaviy-arteom commented on images/background2.png
имя файла нужно исправить и формат

2023-06-19 16:23 UTC, Kartaviy-arteom commented on images/Vector.svg
имя файла нужно исправить

2023-06-19 16:23 UTC, Kartaviy-arteom commented on images/stars.svg
одной звезды достаточно

2023-07-04 09:19 UTC, merged